import type { Metadata } from "next";
import { Work_Sans as WorkSans } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

import QueryProvider from "@/components/providers/query-provider";
import { auth } from "@/features";
import { CustomSessionProvider } from "@/shared/components/custom-session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const workSans = WorkSans({ subsets: ["latin"] });
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session);
  return (
    <html lang="en">
      <body
        className={`
					min-h-screen bg-background  antialiased bg-black
					${workSans.className}`}
      >
        <CustomSessionProvider session={session}>
          <QueryProvider>
            <Navbar />
            <main>{children}</main>
          </QueryProvider>
        </CustomSessionProvider>
      </body>
    </html>
  );
}
