import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./navbar";

import QueryProvider from "@/components/providers/query-provider";
import { auth } from "@/features";
import { CustomSessionProvider } from "@/shared/components/custom-session-provider";
import { Toaster } from "sonner";
import { inter } from "@/shared/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`
					min-h-screen bg-background  antialiased bg-neutral-900
					${inter.className}`}
      >
        <CustomSessionProvider session={session}>
          <QueryProvider>
            <Navbar />
            <main>{children}</main>
            <Toaster />
          </QueryProvider>
        </CustomSessionProvider>
      </body>
    </html>
  );
}
