import type { Metadata } from 'next'
import { Work_Sans as WorkSans } from 'next/font/google'
import './globals.css'
import Navbar from './navbar'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const workSans = WorkSans({ subsets: ['latin'] })
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`
					min-h-screen bg-background  antialiased bg-black
					${workSans.className}`}>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	)
}
